### ISSUE TITLE
Update `alces session` documentation to include new `--geometry`

### ISSUE THREAD

**Issue by vlj91** [alces-software/flight-appliance-docs-openstack#11]
As per title, refs alces-software/clusterware#154

**Comment by mjtko** [comment]
Note this is not available as of 2016.2r3.  We’ll make a decision as to whether to bring this into an r4 or wait until 2016.3.

**Comment by mjtko** [comment]
Closed via c7933b2bbe0d87fee9a7cf8ff07cd5091ec67456
