### ISSUE TITLE
Explain resource limits

### ISSUE THREAD

**Issue by vlj91** [alces-software/flight-appliance-docs-openstack#15]
As above, explain default resource limits and link to additional resource request page

**Comment by wdm78** [comment]
Where (page/reference) in the docs is this bug about? Resource limits are discussed here: http://docs.alces-flight.com/en/updates-aws-launch/sge/sge.html#default-resources - do you think it needs more detail?

**Comment by sierra-tango-echo** [comment]
@vlj91 can you update this please

**Comment by vlj91** [comment]
The page @wdm78 linked is what I was looking for and failed to find, will close this.

**Comment by ste78** [comment]
@vlj91 why only probably?
