### ISSUE TITLE
Update Openfoam tutorial for 2016.2 release

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-appliance-docs-openstack#16]
The following method works:
- Launch a cluster with autoscaling disabled (MinNodes=0)
- Enable the volatile repo (http://docs.alces-flight.com/en/latest/apps/apps.html#volatile-gridware-repositories); comment out the “main” repo
- Run the following commands as your user (takes 45-mins to compile on c4 instance):

```
     pdsh -g cluster 'sudo yum -y install zlib-devel'
     alces gridware install main/mpi/openmpi/1.8.5 qlogic=false torque=false pmi=false pmilib=false sge=true
     alces gridware install libs/scotch
     alces gridware install libs/mgridgen
     alces gridware install openfoam/2.1.1
     alces gridware install paraview/4.3.1
```

To export built packages:

```
alces gridware depot export --ignore-bad local 
```

To import packages on another cluster:

```
for package in mpi-openmpi-1.8.5-el7.tar.gz libs-scotch-6.0.3-el7.tar.gz libs-mgridgen-1.0-el7.tar.gz apps-openfoam-2.1.1-el7.tar.gz apps-paraview-4.3.1-el7.tar.gz
> do
> alces gridware import $package
> done

pdsh -g cluster 'sudo yum -y install zlib-devel'
```

**Comment by vlj91** [comment]
Added the above changes to the OpenFoam tutorial. 

Once OpenFoam versions 2/3 make it through to `main` as well as the supporting packages - we should once again update this to use a simple `alces gridware install openfoam`. 

To-do once packages are in `main`: 
- [ ] remove Alces customiser tool note
- [ ] replace install method
