### ISSUE TITLE
Update AWS launch page for 2016.3 enhancements

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-appliance-docs-openstack#45]
Updates are needed to aws-launch documentation to match new CFN templates for 2016.3 community and enterprise versions.

**Comment by wdm78** [comment]
Also need to update manual launch (I think the setup questions might be different for 2016.3?) and update the URLs to the templates for the template-launch page.

**Comment by vlj91** [comment]
I've not updated the manual launch page, as the process for launching and configuring a single AMI remains the same

**Comment by wdm78** [comment]
Good progress - I've reviewed and here are some comments;

on aws-launch page:
- "how much will it cost" section needs updating to mention flight software costs for non-community version
- need to mention that versions of flight compute ask different launch questions (once product names are finalised)
- under "Cluster administrator username"; change "automatic" to "automatically"
- add links to docs for customisation under "S3 bucket for customization profiles" section
- change "starting a new cluster" to "starting a standard cluster" in customisation profiles section
- change "from a lift of" to "from a list of" in compute node selection section
- if autoscaling is disabled, how does a user set how many compute nodes their cluster has?
- under "Data volume layout", list the four options as bullets or a table below to make more clear
- under "Login node system volume disk type", mention that ssd is faster and magnetic is lower cost
- replace launch screenshot with one that matches the others (i.e. same res/size)
- link to "alces sync" documentation in the "terminating the cluster" section

On manual launch page:
- "alces about identity" command no longer prints cluster secret; update screenshot and/or text to match correct procedure

**Comment by vlj91** [comment]
> how much will it cost" section needs updating to mention flight software costs for non-community version

This section has been updated to reflect the current pricing for a licensed Flight Compute environment, together with the existing text detailing instance/running costs

> need to mention that versions of flight compute ask different launch questions (once product names are finalised)

I haven't included this change as the documentation is centred around the licensed version of Flight Compute

> under "Cluster administrator username"; change "automatic" to "automatically"
> 
> add links to docs for customisation under "S3 bucket for customization profiles" section
> 
> change "starting a new cluster" to "starting a standard cluster" in customisation profiles section
> 
> change "from a lift of" to "from a list of" in compute node selection section

Fixed - thanks!

> if autoscaling is disabled, how does a user set how many compute nodes their cluster has?

The template shown was the development template, and was thus missing a vital field. I've updated everything to use the marketplace-ready template which includes an additional parameter `ComputeMaxNodes`, which allows a user to specify the number of nodes to create even when autoscaling is set to `disabled` - thanks!

> under "Data volume layout", list the four options as bullets or a table below to make more clear
> 
> under "Login node system volume disk type", mention that ssd is faster and magnetic is lower cost
> 
> replace launch screenshot with one that matches the others (i.e. same res/size)
> 
> link to "alces sync" documentation in the "terminating the cluster" section
> 
> "alces about identity" command no longer prints cluster secret; update screenshot and/or text to match correct procedure

Fixed, thanks!

**Comment by wdm78** [comment]
Thanks - I'd rather steer clear of mentioning software costs in the docs though, as it creates another dependency for the future. Can we just change the first bit of text in the "how much will it cost" section to the following?   

The cost for running your cluster will depend on a number of different factors, including the resources you consume and the software you subscribe to. Charges typically fall into the following categories:

( - Include the existing list here)
- Any costs for running the version of Alces Flight that you subscribe to

**Comment by vlj91** [comment]
Good point - made that change, thanks!

**Comment by wdm78** [comment]
Looks good - thanks
