### ISSUE TITLE
Job-scheduler documentation page missing screenshot for interactive job

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-appliance-docs-openstack#47]
SGE page has a screenshot for running an interactive job from a remote desktop; other scheduler pages should have this too. For consistency, keep the cluster name "scooby" in all documentation.

**Comment by wdm78** [comment]
Good text and screenshots, but resolution of pictures is too high - they take too long to load and it's difficult to read the small text. Can we make these the same resolution and file format (JPG) as the SGE doc page please?

**Comment by vlj91** [comment]
Included new session screenshots using the default resolution, and used `jpg` format rather than `png` to reduce the size

**Comment by wdm78** [comment]
Updated screenshots look great - my browser (firefox v48.0.2 on Windows 10) is rendering some of the screenshots with a big black boarder though (picture attached). Can you fix and check that it looks ok on some common browsers? thanks-
![ss1_260916](https://cloud.githubusercontent.com/assets/9553002/18831640/b4120652-83de-11e6-84f3-958edc1dbcf4.jpg)

**Comment by vlj91** [comment]
Ah yes - ImageMagick seemed to make a mess of converting from png.. fixed now - thanks!
