### ISSUE TITLE
Openlava doc page - verify content and sample scripts

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-appliance-docs-openstack#49]
Need to check contents of doc page for OpenLava, particularly;
- need more detail on default location of output files
- use of "%" in sample job-scripts as a shell variable (isn't % for Windows?)
- Check multi-node example - $LSB_HOSTS variable in example script doesn't look right?
- example of requesting more memory

**Comment by vlj91** [comment]
- I've updated information on job output locations - OpenLava will default to the submission directory, as shown in the following example: 

```
[alces@login1(openlava) example]$ bsub < $HOME/mpi_example.sh
Job <106> is submitted to default queue <normal>.
[alces@login1(openlava) example]$ pwd
/home/alces/job-scripts/example
[alces@login1(openlava) example]$ ls
mpi.106
```
- OpenLava accepts the `%` substitutions for scheduler directives, but only within the directives. Both environment variables and the `%` alternatives exist for certain useful dynamic variables such as job IDs etc
- `$LSB_HOSTS` prints a list of the nodes assigned to the job, as per the following example (which also demonstrates the use of the `%` substitution used in the scheduler directives

``` bash
[alces@login1(openlava) ~]$ bsub < mpi_example.sh
Job <105> is submitted to default queue <normal>.
[alces@login1(openlava) ~]$ cat mpi.105
Sender: OpenLava System <openlava@flight-089>
Subject: Job 105: <#!/bin/bash;#BSUB -n 2;#BSUB -R "span[ptile=1]";#BSUB -o mpi.%J;echo $LSB_HOSTS> Done

Job <#!/bin/bash;#BSUB -n 2;#BSUB -R "span[ptile=1]";#BSUB -o mpi.%J;echo $LSB_HOSTS> was submitted from host <login1> by user <alces>.
Job was executed on host(s) <1*flight-089>, in queue <normal>, as user <alces>.
                            <1*flight-090>
</home/alces> was used as the home directory.
</home/alces> was used as the working directory.
Started at Sun Sep 18 16:19:30 2016
Results reported at Sun Sep 18 16:19:30 2016

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
#!/bin/bash
#BSUB -n 2
#BSUB -R "span[ptile=1]"
#BSUB -o mpi.%J
echo $LSB_HOSTS

------------------------------------------------------------

Successfully completed.

Resource usage summary:

    CPU time   :      0.01 sec.
    Max Memory :         2 MB
    Max Swap   :       131 MB

    Max Processes  :         1

The output (if any) follows:

flight-089 flight-090
```
- I've also updated the "Requesting more memory section" to include a simple job script showing the usage of the additional memory request option

**Comment by wdm78** [comment]
Updates look good, but we should also add an explanation of what "%J.%I" does before we use it in an example job-script

**Comment by wdm78** [comment]
Looks good to me - thanks!
