### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/flight-appliance-docs-openstack#62]
A link to an image is broken here: http://docs.alces-flight.com/en/latest/getting-started/environment-usage/run-a-graphical-application.html?highlight=graphical#running-a-graphical-application; not sure what's supposed to go there.

**Comment by ColonelPanics** [comment]
Page no longer part of documentation - https://github.com/alces-software/flight-appliance-docs/issues/66#issuecomment-305827227

From a look at `git log --diff-filter=D` and `git log --all --full-history -- '**/HPC-GraphicalDesktop.png*'` that file has _never_ existed. The older docs are no longer maintained so this issue can be closed.
