### ISSUE TITLE
Update manual launch page to mention loading modules for tools

### ISSUE THREAD

**Issue by wdm78** [alces-software/flight-appliance-docs-openstack#64]
The manual launch docs page should be updated to include info about loading module files to get command-line tools (like aws, pdsh, nodeattr, etc.)

**Comment by ColonelPanics** [comment]
Module load command for pdsh added in e1c53bf536ab782521fe56022145a07ef156be4d to address Issue #60 - unless examples are needed for all of the cli-tools mentioned then this is safe to be closed.
