### ISSUE TITLE
Include AWS command-line launch documentation

### ISSUE THREAD

**Issue by vlj91** [alces-software/flight-appliance-docs-openstack#7]

**Comment by wdm78** [comment]
Don't need this is 2016.2 - I've opened another issue for launching a single instance using the Flight AMI, which does need to be in 2016.2 - https://github.com/alces-software/flight-appliance-docs/issues/21

**Comment by wdm78** [comment]
Requirement that led to this issue has gone away for now, and will be addressed in a future product. Closing this issue
